# Generated by Django 4.0.3 on 2022-03-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('users', '0002_remove_user_timestampzone_ptr_delete_timestampzone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('timestampzone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.timestampzone')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=2000)),
                ('phone_number', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
            bases=('utils.timestampzone',),
        ),
    ]
